---
title: "Homework 4"
author: "Joseph Froelicher"
date: November 1, 2021
output: pdf_document
header-includes:
  - \usepackage{amsmath}
  - \usepackage{geometry}
  - \usepackage{lscape}
---

\section{Question 1}

$$
\textbf{Z}_{(3, 2)}=\left[\begin{array}{cc}
1&0\\
1&1\\
1&2\\
\end{array}\right],\:
\textbf{G}_{(2, 2)}=\left[\begin{array}{cc}
\sigma_1^2&\sigma_{12}\\
\sigma_{12}&\sigma_2^2\\
\end{array}\right],\:
\textbf{R}_{(3, 3)}=\left[\begin{array}{ccc}
\sigma_\epsilon^2&0&0\\
0&\sigma_\epsilon^2&0\\
0&0&\sigma_\epsilon^2\\
\end{array}\right]
$$

$$
\textbf{ZG}_{(3, 2)}=\left[\begin{array}{cc}
\sigma_1^2&\sigma_{12}\\
\sigma_1^2+\sigma_{12}&\sigma_{12}+\sigma_2^2\\
\sigma_1^2+2\sigma_{12}&\sigma_{12}+2\sigma_2^2\\
\end{array}\right],\:
\textbf{Z}^T_{(2, 3)}=\left[\begin{array}{ccc}
1&1&1\\
0&1&2\\
\end{array}\right]
$$

$$
\textbf{ZGZ}^T_{(3, 3)}=\left[\begin{array}{ccc}
\sigma_1^2&\sigma_1^2+\sigma_{12}&\sigma_1^2+2\sigma_{12}\\
\sigma_1^2+\sigma_{12}&\sigma_1^2+2\sigma_{12}+\sigma_2^2&\sigma_1^2+3\sigma_{12}+2\sigma_2^2\\
\sigma_1^2+2\sigma_{12}&\sigma_1^2+3\sigma_{12}+2\sigma_2^2&\sigma_1^2+4\sigma_{12}+4\sigma_2^2\\
\end{array}\right]
$$

$$
\textbf{V}_{(3, 3)}=\textbf{ZGZ}^T+\textbf{R}=\left[\begin{array}{ccc}
\sigma_1^2+\sigma_\epsilon^2&\sigma_1^2+\sigma_{12}&\sigma_1^2+2\sigma_{12}\\
\sigma_1^2+\sigma_{12}&\sigma_1^2+2\sigma_{12}+\sigma_2^2+\sigma_\epsilon^2&\sigma_1^2+3\sigma_{12}+2\sigma_2^2\\
\sigma_1^2+2\sigma_{12}&\sigma_1^2+3\sigma_{12}+2\sigma_2^2&\sigma_1^2+4\sigma_{12}+4\sigma_2^2+\sigma_\epsilon^2\\
\end{array}\right]
$$

$$Cov[Y_{i1}, Y_{i2}] > Cov[Y_{i1}, Y_{i3}]$$
$$\implies \sigma_1^2+\sigma_{12} > \sigma_1^2+2\sigma_{12}$$
$$\implies 0>\sigma_{12}$$
$Cov[Y_{i1}, Y_{i2}] > Cov[Y_{i1}, Y_{i3}]$ holds true if $\sigma_{12}$ is negative. That is the covariance parameter $\sigma_{12}$, which is the covariance between the random intercept and random slope, from the $\textbf{G}$ matrix is negative.

$$Cov[Y_{i1}, Y_{i3}] < Cov[Y_{i2}, Y_{i3}]$$

$$\implies \sigma_1^2+2\sigma_{12}<\sigma_1^2+3\sigma_{12}+2\sigma_2^2$$
$$\implies 0<\sigma_{12}+2\sigma_2^2$$
$$\implies |\:\sigma_{12}\:|<2\sigma_2^2$$
$Cov[Y_{i1}, Y_{i3}] < Cov[Y_{i2}, Y_{i3}]$ holds true if $|\:\sigma_{12}\:|<2\sigma_2^2$. That is the absolute value of the covariance parameter $\sigma_{12}$, which is the covariance between the random intercept and random slope, from the $\textbf{G}$ matrix is is less than twice the variance parameter $\sigma_2^2$ from the same $\textbf{G}$ matrix, which is the variance of the random slope.
\newpage
\section{Question 2}
\subsection{Part A}
\begin{verbatim}
/* Question 2 */
/* Import data */ 
proc import datafile = 'C:\Users\jofro\dev\longi\data\p1np.csv'
 out = data
 dbms = CSV;
run;

/* Question A */
/* UN@UN structure */
/* Doesn't converge, infinite likelihood */
proc mixed data=data method=ml;
  class day time;
  model p1np=day time day*time / solution;
  repeated day time / type=un@un subject=id r rcorr;
run;

/* UN@AR(1) */
proc mixed data=data method=ml;
  class day time;
  model p1np=day time day*time / solution;
  repeated day time / type=un@ar(1) subject=id r rcorr;
run;

/* UN@CS */
/* better AIC */
proc mixed data=data method=ml;
  class day time;
  model p1np=day time day*time / noint solution;
  repeated day time / type=un@cs subject=id r rcorr;
run;
\end{verbatim}

The Kronecker Prodcut structure I chose was unstructured times compound symmetry (UN $\otimes$ CS). This structure was chosen based on  the a lower AIC value of that structure.

\subsection{Part B}

The variance between measurements on day 6 (199.55) is lower than the variance between measurements on day 1 (216.38). There is higher within day correlation than between day correlation, and correlation within days is the same between days (0.18). There is a higher correlation for the same time point between days (0.133) than difference time points between days (0.024).

\begin{verbatim}
/* Question C */
proc mixed data=data method=ml;
  class day time;
  model p1np=day time day*time / noint solution;
  random intercept / subject=id v vcorr;
run;
\end{verbatim}

The biggest mathematical difference between the mdoel without a random intercept and a model with the random intercept is the \textbf{V} matrix is no longer equivalent to the \textbf{R} matrix. By adding a random intercept, the $\textbf{ZGZ}^T$ is no longer the $\textbf{0}$ matrix. The random intercept is inducing higher between and within day correlation (0.20), and it is the same between and within days.. It is also assuming higher variance for day for both days (211.66) and is the same between and within days. The random intercept model is resulting in a better AIC (6332) than the model with no random intercept (6353).

\begin{verbatim}
/* Question D */
data data2;
  set data;
  timec = time;
run;

proc mixed data=data2 method=ml;
  class day time;
  model p1np=day timec day*timec / noint solution;
  repeated day time / type=un@cs subject=id r rcorr;
run;

proc mixed data=data2 method=ml;
  class day time;
  model p1np=day timec day*timec day*timec*timec / noint solution;
  repeated day time / type=un@cs subject=id r rcorr;
run;
\end{verbatim}

The AIC of the linear time model was 6367, and the AIC of the quadratic time model was 6329. The quadratic model seems to be fitting the data significantly better than the linear model according to AIC.

\begin{verbatim}
/* Question E */
proc mixed data=data2 method=reml;
  class day time;
  model p1np=day day*timec day*timec*timec / noint solution;
  repeated day time / subject=id type=un@cs r rcorr;
  contrast "linear trend" day*timec 0 1;
  contrast "linear trend 2" day*timec -1 1;
  contrast "quadratic trend" day*timec*timec 0 1;
  contrast "trend" day*timec 0 1,
  				   day*timec*timec 0 1;
  contrast "treatment vs. reference" day*timec -1 1,
  									 day*timec*timec -1 1;
run;
\end{verbatim}

Using the better performing quadratic time model the custom test of the interaction between treatment intervention and linear time term, and treatment intervention and quadratic time term had a significant result (p < 0.0001). In general there is higher collagen levels on day 6 than day 1, and there is a more interesting quadratic effect of time for day 6 (-0.3118) than day 1 (0.1169).
\newpage
\begin{landscape}
\section{Question 3}

$$
\textbf{Z}_{h(8, 4)}=\left[\begin{array}{cccc}
1&1&0&0\\
1&1&0&0\\
1&1&0&0\\
1&0&1&0\\
1&0&1&0\\
1&0&1&0\\
1&0&0&1\\
1&0&0&1\\
\end{array}\right],\:
\textbf{G}_{h(4, 4)}=\left[\begin{array}{cccc}
\sigma_{int}^2&0&0&0\\
0&\sigma_{h(1)}^2&0&0\\
0&0&\sigma_{h(2)}^2&0\\
0&0&0&\sigma_{h(3)}^2\\
\end{array}\right],\:
\textbf{R}_{h(8, 8)}=\left[\begin{array}{cccccccc}
\sigma_\epsilon^2&0&0&0&0&0&0&0\\
0&\sigma_\epsilon^2&0&0&0&0&0&0\\
0&0&\sigma_\epsilon^2&0&0&0&0&0\\
0&0&0&\sigma_\epsilon^2&0&0&0&0\\
0&0&0&0&\sigma_\epsilon^2&0&0&0\\
0&0&0&0&0&\sigma_\epsilon^2&0&0\\
0&0&0&0&0&0&\sigma_\epsilon^2&0\\
0&0&0&0&0&0&0&\sigma_\epsilon^2\\
\end{array}\right]
$$

$$
\textbf{V}_h = \textbf{ZGZ}^T +\textbf{R}=
$$

$$
\left[\begin{array}{cccccccc}
\sigma_{int}^2+\sigma_{h(1)}^2+\sigma_\epsilon^2&\sigma_{int}^2+\sigma_{h(1)}^2&\sigma_{int}^2+\sigma_{h(1)}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2\\
\sigma_{int}^2+\sigma_{h(1)}^2&\sigma_{int}^2+\sigma_{h(1)}^2+\sigma_\epsilon^2&\sigma_{int}^2+\sigma_{h(1)}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2\\
\sigma_{int}^2+\sigma_{h(1)}^2&\sigma_{int}^2+\sigma_{h(1)}^2&\sigma_{int}^2+\sigma_{h(1)}^2+\sigma_\epsilon^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2\\
\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2+\sigma_{h(2)}^2+\sigma_\epsilon^2&\sigma_{int}^2+\sigma_{h(2)}^2&\sigma_{int}^2+\sigma_{h(2)}^2&\sigma_{int}^2&\sigma_{int}^2\\
\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2+\sigma_{h(2)}^2&\sigma_{int}^2+\sigma_{h(2)}^2+\sigma_\epsilon^2&\sigma_{int}^2+\sigma_{h(2)}^2&\sigma_{int}^2&\sigma_{int}^2\\
\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2+\sigma_{h(2)}^2&\sigma_{int}^2+\sigma_{h(2)}^2&\sigma_{int}^2+\sigma_{h(2)}^2+\sigma_\epsilon^2&\sigma_{int}^2&\sigma_{int}^2\\
\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2+\sigma_{h(3)}^2+\sigma_\epsilon^2&\sigma_{int}^2+\sigma_{h(3)}^2\\
\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2&\sigma_{int}^2+\sigma_{h(3)}^2&\sigma_{int}^2+\sigma_{h(3)}^2+\sigma_\epsilon^2\\
\end{array}\right]
$$
\end{landscape}
